### ISSUE TITLE
Include files to build wso2am version 2.1.0

### ISSUE THREAD

**Issue by memorais** [wso2-attic/puppet-modules#102]
The latest version of wso2am (2.1.0) isn't included in the puppet files yet. It's possible to someone update that?

Thanks.

**Comment by chamilad** [comment]
@memorais This repo is in WSO2 Attic. For APIM Puppet related issues, please use https://github.com/wso2/puppet-apim. I believe Puppet changes for APIM 2.1.0 are already released in that repository.

**Comment by memorais** [comment]
Ok, thanks.
