### ISSUE TITLE
Split modules and publish to Forge

### ISSUE THREAD

**Issue by fatmcgav** [wso2-attic/puppet-modules#3]
In order to simplify the work-flow around Puppet and WSO2, would it be possible to get the individual Puppet modules separated into individual Git repos, and published onto the Puppet Forge (https://forge.puppetlabs.com/). 

This will improve visibility of the modules, simplify and encourage community feedback. 

Happy to discuss further or assist where useful...

**Comment by mwaidyanatha** [comment]
Yes. I agree with you. We are working on this.

**Comment by fatmcgav** [comment]
@mwaidyanatha Cheers for the update... I also believe there are some issues with deploying API Manager 1.8.0, but unfortunately I dont have details readily available... 

I'll try and get something more concrete soon :)

**Comment by imesh** [comment]
@fatmcgav We have now redesigned the puppet modules by using Hiera and many other best practices used by the community. This has provided a Vagrant  based environment for implementing puppet modules, improved the readability of the code and reduced the time needed to implement a new module or update an existing (please see the Wiki). We are planning to publish these modules in Puppet Forge soon.

**Comment by fatmcgav** [comment]
@imesh I've just come back round to looking at automating the install of WSO2 AM using Puppet. 

The module updates look like a good start, however it would be beneficial if each Puppet module was in it's own Git repository. That enables tools such as R10K [1] to be used to manage the modules individually... 

Also, I've got some reservations around the usage of Hiera data, but I'll review and come back to you... 

Cheers
Gavin

[1] https://github.com/puppetlabs/r10k

**Comment by fatmcgav** [comment]
Any progress on getting the modules split into their own repos? 

Cheers

**Comment by imesh** [comment]
@fatmcgav It's nice to hear from you!  Apologies for missing your previous message. 

Just to give you some background information on what happened to our attempt of publishing WSO2 puppet modules to Puppet Forge; currently WSO2 puppet modules are tightly coupled with Hiera. We do hiera data lookups inside puppet modules [1]. At the time when we tried to publish the modules to Puppet Forge, we found that the standard is to loosely couple them.

Regarding splitting modules into separate Git repositories; as I found with r10k; it seems to be a requirement of Puppetfile to have separate repositories for version controlling. We are okay to proceed with that approach but before doing that we may need to discuss it in WSO2 Dev mailing list.

Will you be able to join for a call (may be via a Google Hangout) to discuss these concepts in detail? If so can you please propose a time?

[1] https://github.com/wso2/puppet-modules/blob/master/modules/wso2base/manifests/init.pp

Thanks

**Comment by imesh** [comment]
@fatmcgav We have now started this effort, please feel free to join the discussion at [1]. You may need to join the WSO2 Architecture mailing list [2]. Thanks!

[1] http://mail.wso2.org/mailarchive/architecture/2016-August/025248.html
[2] http://wso2.com/mail/

**Comment by fatmcgav** [comment]
@imesh Cheers for the links... 

One quick comment... 'base' is quite a common 'site' specific module, therefore it's likely to clash across multiple installations. 

Would suggest using something like 'wso2base' as the module name. 

Gav
