### ISSUE TITLE
Move clustering configs to default.yaml 

### ISSUE THREAD

**Issue by udaraliyanage** [wso2-attic/puppet-modules#76]
Hi,

In some products such as ESB and AM clustering config hieradata are duplicated in master.yaml and worker.yaml . Shall we move them to default.yaml since it is unlikely that worker and manager have different clustering configs. Duplicating configs confuses new users and maintainance is harder.

**Comment by imesh** [comment]
A good suggestion Udara! 

I think currently there is an issue doing this; the marathon application names which we should provide under clustering section differs in default profile and other profiles.
