### ISSUE TITLE
Troubles with the reference to java class on hieradata/common.yaml

### ISSUE THREAD

**Issue by falconmfm** [wso2-attic/puppet-modules#86]
This change has not been documented in the wiki , and I need some more  information about how to set up the java_class in hieradata node file. 

After the last change I can't deploy with the wso2base::java reference to java_class andalways get this message...

Error: Could not find data item java_class in any Hiera data file and no default supplied at modules/wso2base/manifests/init.pp:21 on node myserver

**Comment by Thanu** [comment]
The 'java_class' hiera key is defined in [common.yaml](https://github.com/wso2/puppet-modules/blob/v2.1.0/hieradata/dev/common.yaml). Make sure you have the common.yaml file in hieradata path and it's added to hierarchy as in [hiera.yaml file](https://github.com/wso2/puppet-modules/blob/v2.1.0/hiera.yaml#L24). This change is done to plug in any third party class which is responsible for installing java and by default it's set to wso2base::java class.

Will add this change to [Puppet Modules doc](https://docs.wso2.com/display/PM210/WSO2+Puppet+Modules+Documentation).

Thanks.
