### ISSUE TITLE
admin:admin credentials are hardcoded in v2.0.0 jndi.properties file.

### ISSUE THREAD

**Issue by isamauny** [wso2-attic/puppet-modules#96]
See: puppet-modules/modules/wso2am/templates/2.0.0/repository/conf/jndi.properties.erb

connectionfactory.TopicConnectionFactory = amqp://**admin:admin**@clientid/carbon?brokerlist='tcp://<%= @apim_traffic_manager['host'] %>:<%= @apim_traffic_manager['jms_url_port'] %>'

admin:admin needs to be parametrized as well.

**Comment by imesh** [comment]
Thanks for reporting this Isabelle, will fix this in puppet-apim repository:
https://github.com/wso2/puppet-apim/blob/master/templates/repository/conf/jndi.properties.erb#L19
